scan_filter_chain:
- name: shadows
  type: ScanShadowsFilter
  params:
    min_angle: 0
    max_angle: 270
    neighbors: 20
    window: 1
- name: dark_shadows
  type: LaserScanIntensityFilter
  params: 
    lower_threshold: 50
    upper_threshold: 10000
    disp_histogram: 0
